name: gotenberg
icon: gotenberg
type: service
title: Gotenberg
options:
- version: '8'
  tag: '8.6.0'
endpoints:
- name: gotenberg
  ports:
  - name: gotenberg
    number: 3000
    protocol: http
labels:
- gotenberg
- print

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/gotenberg
  chart: oci://registry-1.docker.io/wodby/gotenberg
  version: 0.1.0
workloads:
- id: main
  kind: deployment
  primary: true
  containers:
  - name: gotenberg
    image: gotenberg/gotenberg
    helm:
      resources: resources
      env: envVars
      mounts: extraVolumeMounts
  helm:
    labels: podLabels
    annotations: podAnnotations
    volumes: extraVolumes
